-- Grant permissions to dentist user
GRANT ALL PRIVILEGES ON DATABASE dentist_newdb TO dentist;
GRANT ALL PRIVILEGES ON SCHEMA public TO dentist;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO dentist;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO dentist;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO dentist;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO dentist;
